apiVersion: v1
kind: Service
metadata:
  name: flask-hello-world-service
spec:
  type: NodePort
  selector:
    app: flask-hello-world
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
