apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-mysql.fullname" . }}-flask
  labels:
    app: {{ include "flask-mysql.name" . }}-flask
spec:
  replicas: {{ .Values.flask.replicas }}
  selector:
    matchLabels:
      app: {{ include "flask-mysql.name" . }}-flask
  template:
    metadata:
      labels:
        app: {{ include "flask-mysql.name" . }}-flask
    spec:
      containers:
        - name: flask
          image: {{ .Values.flask.image }}
          ports:
            - containerPort: {{ .Values.flask.service.targetPort | default 5000 }}
          env:
            - name: DB_HOST
              value: {{ printf "%s-%s" (include "flask-mysql.fullname" .) "mysql" | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "flask-mysql.fullname" . }}-mysql-secret
                  key: mysql-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "flask-mysql.fullname" . }}-mysql-secret
                  key: mysql-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "flask-mysql.fullname" . }}-mysql-secret
                  key: mysql-database
