apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-mysql.fullname" . }}-mysql-secret
type: Opaque
stringData:
  mysql-root-password: "{{ .Values.mysql.rootPassword | quote }}"
  mysql-database: "{{ .Values.mysql.database | quote }}"
  mysql-user: "{{ .Values.mysql.user | quote }}"
  mysql-password: "{{ .Values.mysql.password | quote }}"
