apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-mysql.fullname" . }}-mysql
spec:
  type: ClusterIP
  selector:
    app: {{ include "flask-mysql.name" . }}-mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
